project:
  type: book
  output-dir: docs

book:
  title: "LearningDairy"
  author: "Yuhan Liao"
  date: "1/25/2023"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2-portfolio.qmd
    - Week3-corrections.qmd
    - Week4-policy.qmd
    - Week5-GEE.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

