---
title: "Introduction to Remote Sensing"
editor: visual
---

## Summary

### Learning Objectives

1.  Have a basic idea of remote sensing

2.  Have a understanding of remote sensing data

### Remote Sensors

A remote sensor system it the instrument designed to detect and measure physical phenomena or environmental conditions from a distance. Remote sensors could be divided into two types as follow:

-   Passive sensors systems: receive reflected energy

-   Active sensors systems: emit electromagnetic waves, such as SAR

### Electromagnetic waves

The electromagnetic waves are used by remote sensors to detect and measure physical phenomena, also the carriers of information.

The basic properties of electromagnetic waves include wave length($\lambda$), velocity( $c$,rate of oscillation), frequency($v = 3\times10^8 m/s$). They follow the relationship that $\lambda = c/v$.

#### Related jargon

There are also some jargon about electromagnetic waves we need to know:

-   Electromagnetic radiation(EMR): waves of an electromagnetic field, travel through space and carry radiant

-   radiant energy: energy carried by EMR waves

-   radiant flux: energy per unit of time

-   shortwave radiation: energy from the sun

-   solar irradiacne: energy or solar power from the sun per unit area per unit time

-   exitance/emmittance: energy leaving a surface per unit per unit time

#### Interactions with Earth

-   surface

    BRDF

    Polarization

    Fluorensence

-   atmospheric

    Rayleigh

    Mie

    Non selective

### Remote Sensing Data

#### Data formats

#### Four resolutions

Spatial Resolution

Spectral Resolution

Radiometric Resolution

Temporal Resolution

## Application

## Reflection
